#!/usr/bin/env python

import sys
import os

desired = []

with open(sys.argv[1], "r") as f:
    lines = f.readlines()
    for line in lines:
        if "#" in line:
            output = line[line.index("#") + 1:].lstrip().rstrip()
            desired.append(output)

result = os.system("/usr/bin/env sh " + sys.argv[1] + " 1> " + sys.argv[2] + " 2> " + sys.argv[3])
if result:
    exit(1)

with open(sys.argv[2], "r") as f:
    with open(sys.argv[3], "a+") as err:
        lines = f.readlines()
        lineno = 1
        for correct, line in zip(desired, lines):
            if line is None and correct is not None:
                err.write("Output mismatch on line " + str(lineno) + ": expected '" + correct + "' but found empty line.\n")
                f.close()
                err.close()
                exit(1)
            trimmed = line.lstrip().rstrip()
            if trimmed != correct:
                err.write("Output mismatch on line " + str(lineno) + ": expected '" + correct + "' but found '" + trimmed + "'.\n")
                f.close()
                err.close()
                exit(1)
            lineno += 1